Switched to removing Orginal dir mode

diff --git a/lock b/lock
--- a/lock
+++ b/lock
@@ -158,12 +158,21 @@ else
 
     if [[ $? -eq 0 ]]; then
         echo -e "${GREEN}Encryption successful!${NC}"
-        echo -e "${YELLOW}Removing the tar file!${NC}"
+        
+        
         echo -e "${GREEN}Wrote file to ${encrypted_file} ${NC}"
-        echo -e "${YELLOW}Note: We didn't remove the original directory please remove it yourself${NC}"
+       # echo -e "${YELLOW}Note: We didn't remove the original directory please remove it yourself${NC}"
+       #dk might make a question for removal
+        echo -e "${YELLOW}trying tp remove the tar file!${NC}"
         rm "$archive_name"
         if [[ $? != 0 ]]; then 
             echo -e "${RED}Error: can't remove the archive  Please remove it yourself"
+            exit 1
+        fi
+        echo -e "${YELLOW}trying to remove the original dir!${NC}"
+        rm -rf "$plainTextDir"
+        if [[ $? != 0 ]]; then 
+            echo -e "${RED}Error: can't plain Dir  Please remove it yourself"
             exit 1
         fi
     else
